# Generated by Django 4.1.3 on 2022-12-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.topic', verbose_name='Тема'),
        ),
    ]
