# Generated by Django 4.1.3 on 2022-12-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_alter_test_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsusers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_users', to='quiz_api.test', verbose_name='Тест'),
        ),
    ]
