# Generated by Django 4.1.3 on 2022-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_alter_testsusers_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название теста'),
        ),
    ]
