# Generated by Django 4.1.3 on 2022-12-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0004_test_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Варинант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testsusers',
            options={'verbose_name': 'Пользователь и результат тестов', 'verbose_name_plural': 'Пользователи и результаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
